# Site settings
title: Paderborner Kneipenplan
email: ljan@mail.upb.de
description: "Basierend auf dem Kneipenplan der Fachschaft Mathematik/Informatik mit
deren freundlicher Genehmigung. Die Live-Version ist unter http://codeforpb.github.io/Kneipenplan/
zu finden."
baseurl: "/Kneipenplan"
url: "http://codeforpb.github.io/Kneipenplan/"

# Build settings
markdown: kramdown
permalink: pretty
